### ISSUE TITLE
Feat: 회원가입 / 로그인 기능 구현

### ISSUE THREAD

**Issue by sieunnnn** [sieunnnn/app#1]
# TODO
## View 생성
- 각 뷰에서 상단의 prev 버튼을 누르면 이전으로 돌아가야 한다.
- close 버튼을 누르면 현재는 로그인 페이지로 돌아간다.
  - 차후에는 어디로 돌아가야하는지 논의 필요. 
### 로그인 View 
- 현재는 splash view 가 3 초 나오고 로그인으로 바로 이동하게 되어있다.
- 로그인 페이지에서 prev 하면 어디로 가야할지 논의 필요.
### 회원가입 뷰
- [ ] **[phase1]** 권한 동의 view
- [x] **[phase2]** 이메일 입력 view
- [x] **[phase3]** 비밀번호 입력 view
- [x] **[phase4]** 본인인증 view
- [x] **[phase5]** 완료 view

### 로그인
- [x] 일반로그인
- [x] 구글 로그인
- [x] 카카오 로그인
### 회원가입
- [x] 이메일 검증
- [x] 회원가입
- [x] 닉네임 return 받기
  - 자동로그인 처리를 할지 로그인 페이지로 리다이렉트 해야할지 논의 필요.

**Comment by sieunnnn** [comment]
# 24. 08. 31 Validation
- 조건이 만족하지 않았음에도 불구하고 next 버튼이 동작하는 이슈
  - 색 활성화의 경우 제대로 동작

**Comment by sieunnnn** [comment]
## 24. 09. 01 Validation
### 닉네임이 길어지면 화면에서 벗어나는 이슈
<image src="https://github.com/user-attachments/assets/f16edc70-72a0-4d38-b5a9-f3fa34b10f67" width=200/>
<image src="https://github.com/user-attachments/assets/1876178c-4d34-4a6a-b11e-912dfbdee12b" width=200/>
- 닉네임이 길어지면 화면에서 벗어나는 이슈 존재
- 일단 오른쪽과 같이 처리했으나, 논의 필요

**Comment by sieunnnn** [comment]
# TODO
- [ ] 권한 동의와 온보딩 디자인 확인

**Comment by sieunnnn** [comment]
# 24. 09. 03
레이아웃 반응형으로 변경하였습니다.

<img src="https://github.com/user-attachments/assets/891170d5-af49-429d-9471-1c433ed09296" height=400/>
<img src="https://github.com/user-attachments/assets/99c04e53-7164-4d80-afd8-165a5a05a08f" height=400/>
