### ISSUE TITLE
Feat: 홈 화면 기능 구현

### ISSUE THREAD

**Issue by sieunnnn** [sieunnnn/app#5]
# TODO
## View 생성
- [x] home view 생성
- [x] 투두리스트 view 생성
- [x] 코스 view 생성
- [x] 산책로 view 생성
  - [x] 산책로 모두 보기 view 생성
  - [x] 산책로 상세 보기 view 생성
     - 상세보기 안의 리뷰 남기기 detail 문의
- [x] 제주소식 view 생성
  - 현지인 추천 장소 상세 보기 view 문의
    - 반복되는 요소가 있는가?
    - 관리자가 글을 작성해야하는 view 가 필요한가?
  - 제주도 걷기 대회 상세 view 어디에 있는지 문의

### 투두 리스트
> 드래그앤 드롭 기능은 문의하기
- [x] 투두리스트 get api 연결
- [x] 투두리스트 check api 연결
- [x] 생성 api 연결
- [x] 수정 api 연결
- [x] 삭제 api 연결

### 날씨
- 정확한 기능명세 문의하기

**Comment by sieunnnn** [comment]
# 24. 09. 11 Validation
글씨와 아이콘을 다양하게 배치해봤는데, 화면이 작을때 문제가 생겨서 리뷰 수를 표시하는 괄호를 제거하였습니다.

<img src="https://github.com/user-attachments/assets/da44f795-badf-4551-9cd7-dd04c99b9b7c" width=300/>
<img src="https://github.com/user-attachments/assets/a06de294-b5b5-4e36-824e-e763c5e2a0bd" width=300 />

**Comment by sieunnnn** [comment]
## 24. 09. 13 Validation
fold 로 실행했을 때 아래와 같이 반응형이 그닥 이쁘지 않아서 maxWidth 를 조절해야 할 듯 싶습니다.

<img src="https://github.com/user-attachments/assets/9117b601-e287-41ac-bcdf-e652c6b1fa5c" width=600 />

**Comment by sieunnnn** [comment]
## 백엔드 코드 변경
- [ ] 회원가입 시 Todo 생성하면서 기본 Todo 넣는 service 생성하기
