### ISSUE TITLE
Design: 탭 별 frame / view 생성

### ISSUE THREAD

**Issue by sieunnnn** [sieunnnn/app#7]
# TODO
- 지도 view 의 경우 나중에 한번에 처리할 예정
- 지도 api 비교하기
- adapter 최대한 재활용
- 폴더 구조, string, naming 처리, api 분리는 차후에 하기

## 추천 탭
- [x] 코스 추천 fragment

## 검색 탭
- [x] 코스 검색 fragment
  - 라벨 검색 플로우 문의 필요
  - 일단 왼쪽 기준으로 fragment생성
- [x] 코스 검색 activity view
  - 올레길에도 리뷰 라벨 먹일 것인가?
  - 대분류 > 중분류 > 소분류 순 선택을 해야한다.
  - 최신순 / 인기순 / 추천 라벨은 일단 제외
  - 초기화 버튼은 필요가 없다.
- [x] 코스 검색 결과 activity view

### 메인
- [ ] 같이 걷고 메인 view 
- [ ] 동행 찾기 sub fragment
  - [ ] 같이 걷고 상세 view
  - [ ] 동행 찾기 작성 view
- [ ] 채팅 sub fragment
  - [ ] 채팅 리스트 sub fragment
  - [ ] 채팅 view
  - [ ] 차단 view

### 검색
- [ ] 검색 fragment

### 알림
- [ ] 알림 view

## 마이걷고 탭
- 디자이너 분들이 작업 중이라, 차후에 투두리스트 작성 예정

**Comment by sieunnnn** [comment]
## 2024. 09. 15 Validation
- 화면 구현 일부 수정해야함
- 필터 아이콘을 눌렀을때 대분류, 대분류에 따른 중분류, 소분류가 나오도록 수정
  - 필터 아이콘을 누르면 필터 아이콘 행이 사라지고, 다른 대분류 행이 나타난다.
  - 행에서 선택한 대분류에 따라 중분류와 소분류가 담긴 레이아웃이 달라진다.
- 일부 버튼 활성화 안먹히는 이슈 존재. (다 안쓴듯)
- 이전 버튼 추가해서 다시 레이아웃 원복할수 있도록 수정
- 소분류 맨 마지막 버튼 마진 right 으로 변경

**Comment by sieunnnn** [comment]
## 24. 09. 19
### 디자인 수정 완료
- 코스 검색 frame
- 코스 검색 activity view
- 코스 전체 activity view
- 코스 검색 결과 activity view
